"""
Butch the Butcher - Voice Profile
Gruff, warm, knowledgeable, uses meat terminology naturally
"""
import logging
import sys
from pathlib import Path
from typing import Optional
import requests

# Add governance path
GOV_PATH = Path(__file__).resolve().parent.parent.parent / "butch_worker" / "logic"
if str(GOV_PATH) not in sys.path:
    sys.path.append(str(GOV_PATH))

from butch_governance_wrapper import GovernanceWrapper

logger = logging.getLogger(__name__)

class ButchVoice:
    """
    Voice synthesis for Butch with personality injection
    Uses Kokoro primary, Edge backup
    Connects to LLM for dynamic response generation
    """
    
    def __init__(self, api_base: str = "http://localhost:8000", llm_url: str = "http://localhost:11434/api/generate", llm_model: str = "llama2"):
        self.api_base = api_base
        self.llm_url = llm_url
        self.llm_model = llm_model
        self.voice_role = "butch"  # Custom voice mapping
        
        # Initialize governance wrapper - REQUIRED for all LLM integrations
        self.governance = GovernanceWrapper(
            butch_endpoint=self.llm_url,
            llm_model=self.llm_model
        )
        
        # Butch's speech patterns
        self.fillers = ["Alright", "Now", "Listen", "Here's the thing"]
        self.transitions = ["So here's what I'm thinking", "What you want is", "Check this out"]
        self.closers = ["Sound good?", "Make sense?", "Whaddya think?"]
        
    def _call_llm(self, prompt: str) -> str:
        """
        Call the LLM through the governance wrapper - REQUIRED for all LLM integrations
        """
        envelope = self.governance.process(prompt)
        return envelope.butch_response
        
    def introduce(self) -> str:
        """Butch's introduction for new customers - generated by LLM"""
        prompt = (
            "You are Butch the Butcher, a friendly, knowledgeable butcher who loves his job. "
            "Introduce yourself to a new customer visiting Shiloh Ridge Farm. "
            "Be warm, mention your experience, and invite them to ask about meat cuts. "
            "Keep it conversational and under 100 words."
        )
        return self._call_llm(prompt)
    
    def greet_returning(self, customer_name: Optional[str] = None) -> str:
        """Greeting for returning customers - generated by LLM"""
        if customer_name:
            prompt = f"You are Butch the Butcher. Greet a returning customer named {customer_name}. Be friendly and welcoming."
        else:
            prompt = "You are Butch the Butcher. Greet a returning customer warmly, expressing happiness to see them again."
        return self._call_llm(prompt)
    
    def explain_cut(self, cut_name: str, context: str = "general") -> str:
        """Explain a specific cut in Butch's voice - generated by LLM"""
        prompt = (
            f"You are Butch the Butcher, explaining the {cut_name} cut to a customer. "
            f"Be knowledgeable, use meat terminology naturally, be warm and helpful. "
            f"Context: {context}. Keep it conversational and informative."
        )
        return self._call_llm(prompt)
    
    def suggest_optimization(
        self,
        current_selection: list,
        suggestion: str,
        reason: str
    ) -> str:
        """Suggest a change in Butch's conversational style - generated by LLM"""
        prompt = (
            f"You are Butch the Butcher. A customer has selected: {current_selection}. "
            f"Suggest: {suggestion}. Reason: {reason}. "
            f"Be conversational, helpful, and end with a question to confirm."
        )
        return self._call_llm(prompt)
    
    def confirm_order(self, total_weight: float, cut_count: int) -> str:
        """Confirm order details - generated by LLM"""
        prompt = (
            f"You are Butch the Butcher. Confirm an order: {total_weight:.1f} pounds total, {cut_count} different cuts. "
            f"Be reassuring, mention packaging, and ask if they want to adjust anything."
        )
        return self._call_llm(prompt)
    
    def async_speak(self, text: str) -> bytes:
        """
        Generate voice audio via voice service
        Returns MP3 bytes with blockchain signature
        """
        try:
            # Add Butch's personality markers if not present
            if not any(text.startswith(f) for f in self.fillers):
                text = f"Alright, {text[0].lower()}{text[1:]}"
            
            # Add blockchain signature for secure comms
            signature = self._sign_message(text)
            signed_text = f"{text} [SIG:{signature[:16]}]"
            
            response = requests.post(
                f"{self.api_base}/synthesize",
                json={
                    "text": signed_text,
                    "voice_role": "butch",  # Maps to male voice in your system
                    "use_cache": True
                },
                timeout=30
            )
            response.raise_for_status()
            return response.content
            
        except Exception as e:
            logger.error(f"Butch voice generation failed: {e}")
            # Return empty or fallback
            return b""
    
    def _sign_message(self, message: str) -> str:
        """
        Sign message for blockchain communications using Web3
        """
        try:
            from web3 import Web3
            from eth_account import Account
            import os
            
            # Use environment variable for private key, fallback to generated
            private_key = os.getenv('BUTCH_PRIVATE_KEY')
            if not private_key:
                # Generate a deterministic key for demo (in production, use secure key)
                private_key = "0x" + hashlib.sha256(b"butch_blockchain_key").hexdigest()[:64]
            
            account = Account.from_key(private_key)
            message_hash = Web3.keccak(text=message)
            signed = Account.sign_message(message_hash, private_key)
            
            return signed.signature.hex()
        except Exception as e:
            logger.warning(f"Blockchain signing failed: {e}, falling back to hash")
            # Fallback to simple hash if web3 not available
            import hashlib
            key = "butch_fallback_key"
            return hashlib.sha256((message + key).encode()).hexdigest()
    
    def get_chat_bubble_config(self) -> dict:
        """Configuration for frontend chat bubble"""
        return {
            "name": "Butch the Butcher",
            "title": "The Butcher",
            "avatar": "/assets/butch-avatar.png",
            "voice_endpoint": f"{self.api_base}/butch/speak",
            "greeting": self.introduce(),
            "personality": "gruff_but_warm",
            "suggested_prompts": [
                "I want a half hog with extra bacon",
                "What's the difference between shoulder and ham?",
                "How much freezer space do I need?",
                "Can I get more chops and less sausage?"
            ]
        }
